BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Planet] (
    [id] NVARCHAR(1000) NOT NULL,
    [name] NVARCHAR(1000) NOT NULL,
    [description] NVARCHAR(1000) NOT NULL,
    [surfaceArea] FLOAT(53) NOT NULL,
    [sunDistance] FLOAT(53) NOT NULL,
    [durationDay] FLOAT(53) NOT NULL,
    [gravity] FLOAT(53) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [Planet_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [updated_at] DATETIME2 NOT NULL,
    CONSTRAINT [Planet_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
